name: norm-flow-fun
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.6
- jupyter
- jupyterlab
- conda
- scikit-learn
- scipy
- pandas
- numpy
- matplotlib
- seaborn
- pytest
- autograd
- pip:
  - git+https://github.com/ericmjl/fundl
